# Generated by Django 4.2 on 2023-04-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_remove_restaurant_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='is_dog_friendly',
            field=models.BooleanField(default=False),
        ),
    ]
