# Generated by Django 4.2 on 2023-04-19 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dog_friendly', '0001_initial'),
        ('restaurants', '0002_restaurant_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='dog_friendly',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dog_friendly.dogfriendly'),
        ),
    ]
