# Generated by Django 4.2 on 2023-04-19 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_alter_restaurant_dog_friendly'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='dog_friendly',
        ),
    ]
