# Generated by Django 4.2 on 2023-04-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_restaurant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='test',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
