# Generated by Django 4.2 on 2023-04-25 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_restaurant_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='test',
        ),
    ]
