# Generated by Django 4.2 on 2023-04-30 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_alter_restaurant_is_dog_friendly'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='county',
        ),
    ]
