# Generated by Django 4.2 on 2023-04-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DogFriendly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_dog_friendly', models.BooleanField(default=False)),
                ('provides_water_bowls', models.BooleanField(default=False)),
                ('has_doggy_menu', models.BooleanField(default=False)),
            ],
        ),
    ]
