# Generated by Django 4.2 on 2023-04-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog_friendly', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogfriendly',
            name='extras',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dogfriendly',
            name='provides_treats',
            field=models.BooleanField(default=False),
        ),
    ]
