# Generated by Django 4.2 on 2023-04-19 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_remove_restaurant_dog_friendly'),
        ('dog_friendly', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogfriendly',
            name='restaurant',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dog_friendly', to='restaurants.restaurant'),
            preserve_default=False,
        ),
    ]
