# Generated by Django 4.2 on 2023-04-22 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dog_friendly', '0002_dogfriendly_extras_dogfriendly_provides_treats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dogfriendly',
            name='is_dog_friendly',
        ),
    ]
