# Generated by Django 4.2 on 2023-05-04 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('favourites', '0005_remove_favourite_reviews'),
        ('reviews', '0004_review_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='favourites',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='favourites.favourite'),
        ),
    ]
